export interface Payments {
        terminalId: string,
        businessNo: string,
        pgMerchantNo: string,
        tmn: string,
        tmnRF: string,
        myb: string,
        mybRF: string,
        csb: string,
        csbRF: string,
        payco: string,
        paycoRF: string,
        railPlus: string,
        railPlusRF: string,
        zeroPay: string,
        zeroPayRF: string,
        bcNaverPay: string,
        kakaoPayCard: string,
        kakaoPayMoney: string,
        modifyDate: string,
        kcash: string,
        kcashRF: string
}
 // :\s.*,
